name: Commands Shell
on:
  push:
    branches: [master]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: "List files"
        run: |
          pwd
          ls -a
      - name: multiline script
        run: |
          node -v
          npm -v
